language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - cp .env.testing .env

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
